trigger:
 - main

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'dockerHub'
  mapDockerSocket: true
  imageRepository: 'demiguelmoreno/evilpetclinic_c'
  containerRegistry: 'https://hub.docker.com/'
  dockerfilePath: 'Dockerfile'
  tag: '$(Build.BuildId)'
  
  # Agent VM image name
  vmImageName: 'ubuntu-latest'

 steps:
- task: prisma-cloud-compute-scan@3
    inputs:
       scanType: 'images'
       twistlockService: 'demoBuild'
       artifact: '$(imageRepository)'