trigger:
 - main

 pool:
   vmImage: 'ubuntu-latest' 

 variables:
   imageName: 'pipelines-javascript-docker'

 steps:
 - task: Docker@2
   displayName: Build an image
   inputs:
     repository: $(imageName)
     command: build
     Dockerfile: app/Dockerfile
     
- task: prisma-cloud-compute-scan@3
    inputs:
       scanType: 'images'
       twistlockService: 'demoBuild'
       artifact: '$(imageRepository)'